# Generated by Django 5.2.5 on 2025-08-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BorrowingHistory',
            new_name='BorrowHistory',
        ),
    ]
