# Generated by Django 5.2.5 on 2025-08-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_borrowinghistory_borrowhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_on_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
